FROM oceanho/omnilayer/omnicore-baseos:latest

RUN mkdir -p /sources/omnicore /root/omnicore 

COPY ./files/omnicore /sources/omnicore

RUN cd /sources/omnicore && \
    chmod +x ./autogen.sh && \
    sleep 1 && ./autogen.sh && \
    ./configure --without-gui && \
    make && make install && \
    rm -rf /sources

EXPOSE 8832 18332
VOLUME /root/omnicore

ENTRYPOINT ["omnicored", "--datadir=/root/omnicore", "-txindex"]
